apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend
    spec:
      restartPolicy: Always
      containers:
      - name: backend
        image: mraarif/capstone-backend
        ports:
        - containerPort: 8000
        envFrom:
          - secretRef:
              name: dev-secret
        command: [ "/bin/sh" ]
        args: [ "-c", "ls -a && pwd && python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000" ]

      - name: db
        image: postgres:12.0-alpine
        envFrom:
          - secretRef:
              name: dev-secret

      - name: redis
        image: redis:alpine

      - name: celery
        image: mraarif/capstone-celery
        envFrom:
          - secretRef:
              name: dev-secret
        command: [ "/bin/sh" ]
        args: [ "-c", "celery -A headliner worker -l info" ]

      - name: celery-beat
        image: mraarif/capstone-celery-beat
        envFrom:
          - secretRef:
              name: dev-secret
        command: [ "/bin/sh" ]
        args: [ "-c", "celery -A headliner beat -l info" ]

      - name: frontend
        image: mraarif/capstone-frontend
        ports:
          - containerPort: 3000
        envFrom:
          - secretRef:
              name: dev-secret
        command: [ "/bin/sh" ]
        args: [ "-c", "pwd && ls && npm start" ]

