version: 2.1

jobs:
  lint-frontend:
    docker:
      - image: circleci/node:14
    working_directory: /tmp/workspace
    steps:
      - checkout
      - restore_cache:
          keys: [ frontend-build ]
      - run:
          name: lint front-end
          command: |
            cd frontend/headliner
            npm i
            npx eslint src
      - save_cache:
          paths: [ frontend/node_modules ]
          key: frontend-build

  lint-backend:
    docker:
      - image: python:3.8
    working_directory: /tmp/workspace
    steps:
      - checkout
      - run:
          name: lint backend
          command: |
            cd backend
            pip install -r requirements.txt
            pylint headliner

  test-frontend:
    docker:
      - image: circleci/node:14
    working_directory: /tmp/workspace
    steps:
      - checkout
      - restore_cache:
          keys: [ frontend-build ]
      - run:
          name: Front-end test
          command: |
            cd frontend/headliner
            npm i
            npm run test
      - save_cache:
          paths: [ frontend/node_modules ]
          key: frontend-build

  test-backend:
    docker:
      - image: python:3.8
    working_directory: /tmp/workspace
    steps:
      - checkout
      - run:
          name: test backend
          command: |
            cd backend
            pip install -r requirements.txt
            pytest headliner/api/news/tests.py


  build-push-docker-images:
    machine: true
    working_directory: /tmp/workspace
    steps:
      - checkout
      - run:
          name: build images
          command: |
            docker-compose build
      - run:
          name: push to docker hub
          command: |
            docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
            docker push mraarif/capstone-backend
            docker push mraarif/capstone-celery
            docker push mraarif/capstone-celery-beat

  create-kubernetes-cluster:
    docker:
      - image: alpine/k8s:1.15.12
    working_directory: /tmp/workspace
    steps:
      - checkout
      - run:
          name: create kubernetes cluster
          command: |
            mkdir kubeconfig
            touch kubeconfig/kube_config.yaml
            export KUBECONFIG=kubeconfig/kube_config.yaml

            eksctl get cluster | grep capstone-cluster > output.txt
            if [ -s output.txt ]
            then
              echo 'cluster  already exists skipping creation'
            else
              eksctl create cluster -f cluster.yaml
            fi

      - run:
          name: create kubernetes resources
          command: |
            export KUBECONFIG=kubeconfig/kube_config.yaml
            aws eks update-kubeconfig --name capstone-cluster
            cd deploy
            kubectl apply -f dev-secrets.yaml
            kubectl apply -f redis/
            kubectl apply -f db/
            kubectl apply -f backend/
            kubectl apply -f celery/

      - run:
          name: add backend service ip to a file
          command: |
            echo "$(kubectl get services backend-service --output jsonpath='{.status.loadBalancer.ingress[0].hostname}')" >> backend-service.txt
            cat backend-service.txt

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - backend-service.txt
            - kubeconfig/kube_config.yaml

  build-push-frontend-image:
    machine: true
    working_directory: /tmp/workspace
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: build image
          command: |
            docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
            export BACKEND_IP=$(cat backend-service.txt)
            docker-compose build frontend
            docker push mraarif/capstone-frontend

  deploy-frontend-to-cluster:
    docker:
      - image: alpine/k8s:1.15.12
    working_directory: /tmp/workspace
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: update kubernetes cluster resources
          command: |
            export KUBECONFIG=kubeconfig/kube_config.yaml
            cd deploy
            kubectl apply -f frontend/


  smoke-test:
    docker:
      - image: alpine/k8s:1.15.12
    working_directory: /tmp/workspace
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: smoke test frontend and backend services
          command: |
            export KUBECONFIG=kubeconfig/kube_config.yaml
            echo "$(kubectl get services backend-service --output jsonpath='{.status.loadBalancer.ingress[0].hostname}')" >> backend-service.txt
            echo "$(kubectl get services frontend-service --output jsonpath='{.status.loadBalancer.ingress[0].hostname}')" >> frontend-service.txt
            BACKEND_IP=$(cat backend-service.txt)
            FRONTEND_IP=$(cat backend-service.txt)
            curl "http://${BACKEND_IP}:8000/news"
            curl "http://${FRONTEND_IP}:3000"

workflows:
  default:
    jobs:
      - lint-frontend
      - lint-backend
      - test-frontend:
          requires: [ lint-frontend ]
      - test-backend:
          requires: [ lint-backend ]

#      - build-push-docker-images:
#          requires: [ test-frontend, test-backend ]
#          filters:
#            branches:
#              only:
#                - main
      - create-kubernetes-cluster:
          requires: [ test-frontend, test-backend ]
          filters:
            branches:
              only:
                - main

      - build-push-frontend-image:
          requires: [ create-kubernetes-cluster ]

      - deploy-frontend-to-cluster:
          requires: [ build-push-frontend-image ]

      - smoke-test:
          requires: [ deploy-frontend-to-cluster ]
