apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-container
  template:
    metadata:
      labels:
        app: frontend-container
    spec:
      containers:
        - name: backend
          image: mraarif/capstone-frontend
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: dev-secrets
          command: [ "/bin/sh" ]
          args: [ "-c", "npm start" ]
